### ISSUE TITLE
Problem with user access notify

### ISSUE THREAD

**Issue by rvrignaud** [Tauop/sshGate#14]
Hello,
I got an error when I try notify the access for a user :
     sshGate >  user xxx access info
        xxx ---> root@server.exemple.com
     sshGate >  user xxx access notify
        ERROR: Target host '' doesn't exist

Thx !

**Comment by Tauop** [comment]
Romain,
Does this error still exist ?

**Comment by Tauop** [comment]
may be solved by 8c9ad991505185445af2c131612ec15144095736
