### ISSUE TITLE
Session recording problem

### ISSUE THREAD

**Issue by Kydo-zz** [Tauop/sshGate#17]
When I connect to a server through the sshGate server i configured, here are the errors showing  :

/opt/sshgate/bin/core/record.func: line 135: MUTEX_GET: command not found
/opt/sshgate/bin/core/record.func: line 137: MUTEX_RELEASE: command not found
/opt/sshgate/bin/core/record.func: line 79: chwon: command not found
/opt/sshgate/bin/core/record.func: line 142: MUTEX_GET: command not found
/opt/sshgate/bin/core/record.func: line 144: MUTEX_RELEASE: command not found
/opt/sshgate/bin/core/record.func: line 96: MUTEX_GET: command not found
/opt/sshgate/bin/core/record.func: line 98: MUTEX_RELEASE: command not found

I changed the mistyped "chwon" to "chown" but how do I get rid of the other errors ?

Thanks.

**Comment by adedommelin-zz** [comment]
Hi Kido,
I've submitted a pull request (https://github.com/Tauop/sshGate/pull/18) which fix this issue among others.

Bests

**Comment by Tauop** [comment]
Thanks for your returns and your pull request.

sshGate is in a ugly state for the moment, as no release have been done ATM.
I am preparing a release for the next week, which will include the new record functionnalities, with tests.

Regards.

**Comment by Tauop** [comment]
solve in commit 30ddf2757b9c17f91ec1740ac69df624e49ed0d5
