### ISSUE TITLE
Check packages is present

### ISSUE THREAD

**Issue by jgoffaux** [Tauop/sshGate#19]
Hello Patrick !

It's possible to add check packages is installed (sudo / vim) :

Example : 

Configure sudo with NOPASSWD to launch remote admin CLI [Y] ?  
- Reload configuration ... OK
- Installing sshGate ... OK
- Generate default sshkey pair ... OK
- Setup files permissions ... OK
- Install archive cron ... OK
- configure /etc/sudoers ... ./install.sh: line 204: /etc/sudoers: Aucun fichier ou dossier de ce type
  mv: impossible d'évaluer « /tmp/sudoers.4521 »: Aucun fichier ou dossier de ce type

and :

You need to add the first user of sshGate, which will be sshGate administrator.
This user will allow you to manage other users, targets and accesses.
user login ?  jgoffaux
user mail ?  jimmy.goffaux@alterway.fr
/opt/sshgate/bin/core/user.func: line 399: vim : commande introuvable

Thanks

**Comment by Tauop** [comment]
In the installation process, I ask which editor to use, to set SSHGATE_EDITOR, which is used by USER_ADD().
If the admin doesn't reply correctly, it won't work.

What do you want me to do ? check if the binary (answer of "which editor") exist ?

About sudoers, I will remove this ugly dependency.

**Comment by jgoffaux** [comment]
Yes, check if the binary editor is present. This can cause problems on adding a SSh keys public for user;  for example.

**Comment by Tauop** [comment]
OK, so check if there can be an error between the chair and the keyboard :-D
