### ISSUE TITLE
Access to serveur sshGate

### ISSUE THREAD

**Issue by jgoffaux** [Tauop/sshGate#26]
Hello Tauop,

We found a bug that gives us access to the server sshGate

test3@vm:~$ ssh sshgate@SERVER_BASTION IP_TARGET '; hostname' 
bastion
bash: -c: line 0: Erreur de syntaxe pr�s du symbole inattendu � ; �
bash: -c: line 0: `; hostname'
test3@vm:~$ 

We will look to try to find a solution.

Thanks,

**Comment by Tauop** [comment]
Fix as soon as you show me it on Jabber -> commit 8e24f40c7a2a8d86b5615e2f6dae5dbe23778002
