### ISSUE TITLE
File TOS

### ISSUE THREAD

**Issue by jgoffaux** [Tauop/sshGate#28]
Hello,

Can you checker the path to the file : bin/sshgate-bridge  :

<pre>
# check usage condition
if [ "${SSHGATE_USERS_MUST_ACCEPT_TOS}" = 'Y' -a -f "${SSHGATE_TOS_FILE}" ]; then
  has_accept_cgu=$( USER_GET_CONF "${SSHKEY_USER}" HAS_ACCEPT_TOS )
  if [ "${has_accept_cgu}" != 'true' ]; then
    lang=$( USER_GET_CONF "${SSHKEY_USER}" LANGUAGE )
    [ -n "${lang}" ] && lang="${SSHGATE_DEFAULT_LANGUAGE}"

-    cat "${SSHGATE_DIR_TEMPLATES}/${lang}/${SSHGATE_TOS_FILE}"
+   cat "${SSHGATE_TOS_FILE}"

    echo
    ASK --yesno var "-> 'yes' / 'no' ?"
    [ "${var}" = 'N' ] && exit 1;
    USER_SET_CONF "${SSHKEY_USER}" HAS_ACCEPT_TOS 'true'
  fi
fi
</pre>

After installation, and answer to questions : 
SSHGATE_USERS_MUST_ACCEPT_TOS="Y"

For the first authentication is not validated the TOS, 
To fix I had to add in the / etc / sshgate.conf the variable:
SSHGATE_TOS_FILE = "/opt/sshgate/data/templates/fr/TOS.txt"

Jimmy

**Comment by jgoffaux** [comment]
Hello,

Please, reopen this issue : 

<pre>
root@bastion:~# cat /etc/sshgate.conf
[....]
SSHGATE_USERS_MUST_ACCEPT_TOS="Y"
[....]
SSHGATE_DEFAULT_LANGUAGE="fr"
[...]
</pre>


My display conf :

<pre>
sshGate >  user jgoffaux display conf
MAIL="jimmy.goffaux@alterway.fr"
sshGate > 
</pre>


And connection :

<pre>
jgoffaux@pc-jgoffaux:~$ ./sshg server.nexen.net
+++ set +x
++ USER_GET_CONF jgoffaux HAS_ACCEPT_TOS
++ local user= var= file=
++ '[' 2 -ne 2 ']'
++ user=jgoffaux
++ var=HAS_ACCEPT_TOS
++ '[' -z jgoffaux -o -z HAS_ACCEPT_TOS ']'
++ '[' '!' -f /opt/sshgate/users/jgoffaux -o -z jgoffaux ']'
++ file=/opt/sshgate/users/jgoffaux.properties
++ '[' -f /opt/sshgate/users/jgoffaux.properties ']'
++ CONF_GET --conf-file /opt/sshgate/users/jgoffaux.properties HAS_ACCEPT_TOS
++ local result= resultvar= confvar= sep= conf_file= 's=[[:space:]]'
++ true
++ '[' 3 -eq 0 ']'
++ case "$1" in
++ shift
++ conf_file=/opt/sshgate/users/jgoffaux.properties
++ shift
++ true
++ '[' 1 -eq 0 ']'
++ case "$1" in
++ break
++ '[' 1 -eq 0 -o 1 -gt 2 ']'
++ '[' '!' -r /opt/sshgate/users/jgoffaux.properties ']'
++ confvar=HAS_ACCEPT_TOS
++ resultvar=HAS_ACCEPT_TOS
++ '[' -z HAS_ACCEPT_TOS ']'
+++ private_SED_SEPARATOR HAS_ACCEPT_TOSHAS_ACCEPT_TOS
+++ for s in ''\''/'\''' ''\''@'\''' ''\'','\''' ''\''|'\'''
+++ printf %s HAS_ACCEPT_TOSHAS_ACCEPT_TOS
+++ grep /
+++ '[' 1 -ne 0 ']'
+++ printf %s /
+++ return 0
++ sep=/
+++ sed -n -e 's/^[[:space:]]*HAS_ACCEPT_TOS[[:space:]]*=[[:space:]]*\(.*\)[[:space:]]*$/\1/p' /opt/sshgate/users/jgoffaux.properties
++ result=
++ eval HAS_ACCEPT_TOS=
+++ HAS_ACCEPT_TOS=
++ LOG 'CONF_GET: HAS_ACCEPT_TOS='
++ MESSAGE --no-indent --no-print CONF_GET: HAS_ACCEPT_TOS=
++ local do_print=true do_log=true do_indent=true 'cbreak=\n'
++ local msg= date=
+++ date '+[%D %T]'
++ date='[07/28/11 10:13:33]'
++ '[' true ']'
++ '[' 4 -eq 0 ']'
++ case "$1" in
++ shift
++ do_indent=false
++ '[' true ']'
++ '[' 3 -eq 0 ']'
++ case "$1" in
++ shift
++ do_print=false
++ '[' true ']'
++ '[' 2 -eq 0 ']'
++ case "$1" in
++ break
++ msg='CONF_GET: HAS_ACCEPT_TOS='
++ '[' false = true ']'
++ '[' false = true ']'
++ '[' true = true -a -f '' ']'
++ eval 'echo "${HAS_ACCEPT_TOS}"'
+++ echo ''
++ return 0
+ has_accepted=
+ '[' '' '!=' true ']'
++ USER_GET_CONF jgoffaux LANGUAGE
++ local user= var= file=
++ '[' 2 -ne 2 ']'
++ user=jgoffaux
++ var=LANGUAGE
++ '[' -z jgoffaux -o -z LANGUAGE ']'
++ '[' '!' -f /opt/sshgate/users/jgoffaux -o -z jgoffaux ']'
++ file=/opt/sshgate/users/jgoffaux.properties
++ '[' -f /opt/sshgate/users/jgoffaux.properties ']'
++ CONF_GET --conf-file /opt/sshgate/users/jgoffaux.properties LANGUAGE
++ local result= resultvar= confvar= sep= conf_file= 's=[[:space:]]'
++ true
++ '[' 3 -eq 0 ']'
++ case "$1" in
++ shift
++ conf_file=/opt/sshgate/users/jgoffaux.properties
++ shift
++ true
++ '[' 1 -eq 0 ']'
++ case "$1" in
++ break
++ '[' 1 -eq 0 -o 1 -gt 2 ']'
++ '[' '!' -r /opt/sshgate/users/jgoffaux.properties ']'
++ confvar=LANGUAGE
++ resultvar=LANGUAGE
++ '[' -z LANGUAGE ']'
+++ private_SED_SEPARATOR LANGUAGELANGUAGE
+++ for s in ''\''/'\''' ''\''@'\''' ''\'','\''' ''\''|'\'''
+++ printf %s LANGUAGELANGUAGE
+++ grep /
+++ '[' 1 -ne 0 ']'
+++ printf %s /
+++ return 0
++ sep=/
+++ sed -n -e 's/^[[:space:]]*LANGUAGE[[:space:]]*=[[:space:]]*\(.*\)[[:space:]]*$/\1/p' /opt/sshgate/users/jgoffaux.properties
++ result=
++ eval LANGUAGE=
+++ LANGUAGE=
++ LOG 'CONF_GET: LANGUAGE='
++ MESSAGE --no-indent --no-print CONF_GET: LANGUAGE=
++ local do_print=true do_log=true do_indent=true 'cbreak=\n'
++ local msg= date=
+++ date '+[%D %T]'
++ date='[07/28/11 10:13:33]'
++ '[' true ']'
++ '[' 4 -eq 0 ']'
++ case "$1" in
++ shift
++ do_indent=false
++ '[' true ']'
++ '[' 3 -eq 0 ']'
++ case "$1" in
++ shift
++ do_print=false
++ '[' true ']'
++ '[' 2 -eq 0 ']'
++ case "$1" in
++ break
++ msg='CONF_GET: LANGUAGE='
++ '[' false = true ']'
++ '[' false = true ']'
++ '[' true = true -a -f '' ']'
++ eval 'echo "${LANGUAGE}"'
+++ echo ''
++ return 0
+ lang=
+ '[' -n '' ']'
+ tos_file=/opt/sshgate/data/templates//TOS.txt
+ '[' -r /opt/sshgate/data/templates//TOS.txt ']'
+ set +x
</pre>


And files is : /opt/sshgate/data/templates/fr/TOS.txt

**Comment by jgoffaux** [comment]
I have  change in file : core/user.func  : line 553

[ -n "${lang}" ] && lang="${SSHGATE_DEFAULT_LANGUAGE}"
by
[ -n "${lang}" ] || lang="${SSHGATE_DEFAULT_LANGUAGE}"

it's resolv the problem

Jimmy

**Comment by Tauop** [comment]
Yep, just a mistake :-(. I have add one more check too.
Thx Jimmy
