### ISSUE TITLE
Add targetgroups

### ISSUE THREAD

**Issue by jgoffaux** [Tauop/sshGate#29]
Hello Taoup,

It's possible to add function "targetgroup" in the project ?

It would be interesting to add servers in a group of machine.
This will help to save time in the management of ACL.

Thanks.

**Comment by Tauop** [comment]
I have remove targetgroup 6 months ago.

I can rewrite code to deal with targetgroup, if it doesn't add complexity to HAS_ACCESS() functions.

**Comment by Tauop** [comment]
see https://github.com/Tauop/sshGate/tree/targetgroup
beta version

**Comment by Tauop** [comment]
Work in progress.
Close this issue
