### ISSUE TITLE
Why SSHGATE_EDITOR?

### ISSUE THREAD

**Issue by elg** [Tauop/sshGate#30]
Hi,
Actually, $EDITOR is set on common systems and provide a user editor choice. Including a specific editor preference for sshgate seems to void this $EDITOR feature.
## Regards,

Erwan

**Comment by Tauop** [comment]
The default value of $SSHGATE_EDITOR is $EDITOR if set.

Plus, on some system, the $EDITOR isn't set :

<pre>
linagora-arathi:~# uname -a
Linux linagora-arathi 2.6.26-2-amd64 #1 SMP Mon Jun 13 16:29:33 UTC 2011 x86_64 GNU/Linux
linagora-arathi:~# echo $EDITOR

linagora-arathi:~#
</pre>


<pre>
Tauop-Mac:~ Tauop$ uname -a
Darwin Tauop-Mac.local 11.1.0 Darwin Kernel Version 11.1.0: Tue Jul 26 16:07:11 PDT 2011; root:xnu-1699.22.81~1/RELEASE_X86_64 x86_64
Tauop-Mac:~ Tauop$ echo $EDITOR

Tauop-Mac:~ Tauop$
</pre>


<pre>
Tauop-Mac:~ Tauop$ ssh root@gate.par.lng 'uname -a'
Linux gate.par.lng 2.6.18-6-686 #1 SMP Thu Oct 9 15:52:18 UTC 2008 i686 GNU/Linux
Tauop-Mac:~ Tauop$ ssh root@gate.par.lng 'echo $EDITOR'

Tauop-Mac:~ Tauop$ 
</pre>

**Comment by elg** [comment]
1) Sure, a lot of systems don't havec $EDITOR. For them, do a proposition seems well (even if seting $EDITOR system wide would certainly be smart too). But for the other, that's a lost (see 2).

2) I have read the code and seen ${EDITOR} set by default. but actually you set the ${EDITOR} value during the install process instead of jump off the question and let ${EDITOR} in config file. If I prefer "emacs" and another administrator "vim": it would never be possible to use our favorite :)

btw, this is a very low issue, more a question: you can ignore it. I'll maybe purpose a patch if I found time today.

**Comment by Tauop** [comment]
A resumé of your proposition : 
- Set $SSHGATE_EDITOR if $EDITOR has no value
- Doesn't ask about $SSHGATE_EDITOR if $EDITOR exists and set $SSHGATE_EDITOR to $EDITOR.

-> This can be done easily and quickly. Accepted.

it seems to be more usefull to let packager change $EDITOR system wide.

**Comment by Tauop** [comment]
fix by 8bd935fc028cbfb74ed976697c2aedd057da6f07
