### ISSUE TITLE
Default mail not dummy

### ISSUE THREAD

**Issue by elg** [Tauop/sshGate#31]
It's kind of freaking me out to see that "SSHGATE_MAIL_TO='sshgate@linagora.com'" is set in /etc/sshgate.conf after installation and in "sshgate/bin/core/setup.func:","sshgate/bin/tests/sshgate.test.conf" and "sshgate/data/sshgate.conf". Even if I didn't activate mail, seeing some of sensible data go by default to unkown mail address let me think that a little code error can become dramatical (ie: if a mail go out even if I have deactivate mail alert).

I think sshgate is not reliable  while you keep this kind of data in final installation. Please replace by dummy mails (you@yourdomain.tld).

**Comment by Tauop** [comment]
Accepted.
