### ISSUE TITLE
[feature] user can list targets allowed

### ISSUE THREAD

**Issue by sbonnegent** [Tauop/sshGate#32]
For an user, it could be usefull to list all targets allowed.

For example:

> ssh sshgate@my_ssh_gate list targets
> root@server1
> root@server2
> toto@server3

**Comment by Tauop** [comment]
This command is a little buggy for the moment.
It'll be corrected soon

last command was "ssh sshgate@sshgate-server cmd list targets"

You can also notify users about their access with "user <user> access notify"

**Comment by sbonnegent** [comment]
Thank you, this 2 commands will do the job.
