### ISSUE TITLE
Add target not reachable from outside

### ISSUE THREAD

**Issue by rvrignaud** [Tauop/sshGate#7]
Hello,
It would be usefull to be able to add a target and specify directly the proxy server when the target is not reachable from outside. Like :
target add target.name.exemple.com with SSH_PROXY proxy.name.exemple.com

Thx

**Comment by Tauop** [comment]
"target add <target-name> via <proxy-name>" seems to be better, doesn't it ?

**Comment by Tauop** [comment]
this has been pushed on [this commit](https://github.com/Tauop/sshGate/commit/68d28827a9569836969d03ba7476f26f3c0706f4#L6R106), sshgate-cli line 106

Can you tell me what you think about the CLI command syntax ?

**Comment by Tauop** [comment]
available CLI command :
- target add <login>@<target> with proxy <login>@<target>
- target add <login>@<target> via <login>@<target>

must be tester for now.

**Comment by Tauop** [comment]
Feature added since few months now.
