### ISSUE TITLE
CLI del conf

### ISSUE THREAD

**Issue by rvrignaud** [Tauop/sshGate#8]
Hello,
I think that it's more easy to use the command  user del conf CONF_NAME rather than user <user> set conf <var>.

The target help doesn't show how to remove target conf. In the same way it should be target TARGET_NAME del conf CONF_NAME

Thx

**Comment by Tauop** [comment]
commit  a19ec5bf150c62059103562db16720d42751b968

fixed

**Comment by rvrignaud** [comment]
thx
